version: '3'

volumes:
  cln_psql:

services:
  cln_psql:
    image: sdal/cln_psql
    container_name: cln_psql
    volumes:
      - cln_psql:/var/lib/pgsql/9.6/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /home/bjgoode/cln_psql_bkup:/cln_psql_bkup
    cap_add:
      - SYS_ADMIN
    ports:
      - 5434:5432

  cln:
    image: sdal/cln
    container_name: cln
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    ports:
      - 8686:8000
    depends_on:
      - cln_psql
    command: python36 /code/manage.py migrate --noinput
    command: python36 /code/manage.py collectstatic
    command: gunicorn sdal_cln.wsgi:application --bind 0.0.0.0:8000 --workers 3
