version: '2'

# Notes about this docker-compose file
# the R packages are installed within the rpkgs container
# it uses the 'global' `rpkgs` volumne
# The R packages are not installed by default (i.e., in the Dockerfile)
# if you completely tear and remove all containers/volumnes/etc
# remember to exec into the `rpkgs` container and manually install packages
# there is code examples and links to the scripts in the rpkgs Dockerfile

volumes:
  pg_data:
  dkw_data:
  dkw_conf:
  dkw_lib:
  shy_apps:
  rpkgs:

services:
  postgresql:
    image: sdal/pg-ldap-ssh-c7
    container_name: postgresql
    volumes:
      - pg_data:/var/lib/pgsql/9.6/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    ports:
      - 5433:5432

  adminer:
    image: sdal/adminer-httpd-ldap-ssh-c7
    container_name: adminer
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    links:
      - postgresql
    ports:
      - 8080:80

  dokuwiki:
    image: sdal/dkw-httpd-ldap-ssh-c7
    container_name: dokuwiki
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - dkw_data:/var/www/html/dokuwiki/data
      - dkw_conf:/var/www/html/dokuwiki/conf
      - dkw_lib:/var/www/html/dokuwiki/lib
    cap_add:
      - SYS_ADMIN
    ports:
      - 8282:80

  mro:
    image: sdal/mro-ldap-ssh-c7
    container_name: mro
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - rpkgs:/rpkgs
    cap_add:
      - SYS_ADMIN

  rpkgs:
    image: sdal/rpkgs-mro-ldap-ssh-c7
    container_name: rpkgs
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - rpkgs:/home/rpkgs/rpkgs
    cap_add:
      - SYS_ADMIN

  rstudio:
    image: sdal/rss-mro-ldap-ssh-c7
    container_name: rstudio
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
    cap_add:
      - SYS_ADMIN
    ports:
      - 8788:8787

  shiny:
    image: sdal/shy-mro-ldap-ssh-c7
    container_name: shiny
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - shy_apps:/srv/shiny-server/sdal
    cap_add:
      - SYS_ADMIN
    ports:
      - 3839:3838
