version: '3'

# Notes about this docker-compose file
# the R packages are installed within the rpkgs container
# it uses the 'global' `rpkgs` volumne
# The R packages are not installed by default (i.e., in the Dockerfile)
# if you completely tear and remove all containers/volumnes/etc
# remember to exec into the `rpkgs` container and manually install packages
# there is code examples and links to the scripts in the rpkgs Dockerfile

volumes:
  rpkgs:
  checkpoint:

services:
  rstudio_eiriki:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_eiriki
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8752:8787

  rstudio_hsbb8:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_hsbb8
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8751:8787

  rstudio_djliden91:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_djliden91
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8753:8787

  rstudio_davon:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_davon
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8754:8787

  rstudio_sheen:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_sheen
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8756:8787

  rstudio_jbsc:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_jbsc
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8757:8787

  rstudio_dnair1:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_dnair1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8758:8787

  rstudio_fle907:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_fle907
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8759:8787


  rstudio_kelseym8:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_kelseym8
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8720:8787

  rstudio_keren9:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_keren9
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8721:8787

  rstudio_alexan16:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_alexan16
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8722:8787

  rstudio_weerasu3:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_weerasu3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8723:8787

  rstudio_luke3874:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_luke3874
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8724:8787

  rstudio_ragsaw96:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_ragsaw96
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8725:8787

  rstudio_armimo97:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_armimo97
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8726:8787

  rstudio_coryk:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_coryk
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8727:8787

  rstudio_doug2019:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_doug2019
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8728:8787

  rstudio_megang4:
    image: sdal/rss-mro-c7sd_auth
    container_name: rstudio_megang4
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/group:/etc/group
      - /home:/home
      - rpkgs:/rpkgs
      - checkpoint:/checkpoint
    cap_add:
      - SYS_ADMIN
    ports:
      - 8729:8787
