version: '3'

volumes:
  arldhs_etc:
  arldhs_home:
  arldhs_share:
  arldhs_opt:

services:

  rstudio_arldhs:
    image: sdal/rss_external:latest
    container_name: rstudio_arldhs
    mem_limit: 10g
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - arldhs_etc:/etc
      - arldhs_home:/home
      - arldhs_opt:/opt
      - arldhs_share:/home/share
    cap_add:
      - SYS_ADMIN
    ports:
      - 3191:8787

