version: '2'

# Notes about this docker-compose file
# the R packages are installed within the rpkgs container
# it uses the 'global' `rpkgs` volumne
# The R packages are not installed by default (i.e., in the Dockerfile)
# if you completely tear and remove all containers/volumnes/etc
# remember to exec into the `rpkgs` container and manually install packages
# there is code examples and links to the scripts in the rpkgs Dockerfile

volumes:
  ext_etc:
  ext_home:
  ext_share:

services:

  rstudio_arldhs:
    image: sdal/rss_external:latest
    container_name: rstudio_arldhs
    mem_limit: 10g
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ext_etc:/etc
      - ext_home:/home
      - ext_share:/home/share
    cap_add:
      - SYS_ADMIN
    ports:
      - 3191:8787

